## Python Program for n-th Fibonacci number

In [15]:
# 0,1,1,2,3,5,8,13,21
n = 6
num1 = 0
num2 = 1
ans = 0

if n==1:
    ans = num1
elif n==2:
    ans = num2
else:
    for i in range(2, n):
        ans = num1 + num2
        #ans = 2
        num1 = num2
        #num1 = 1
        num2 = ans
        #num2 = 2
print(ans)

5


## Python Program for Sum of squares of first n natural numbers

In [18]:
n = 5
# answer = 1^2 + 2^2 +3^2 + 4^2 + 5^2
answer = 0
for i in range(1,n+1):
    answer = answer + i*i
print(answer)

30


## Python Program to find sum of list

In [19]:
thislist = [2,3,5,2,3]
answer = 0 
for i in thislist:
    answer = answer + i
print(answer)

15


## Python program to find largest number in a list

In [26]:
thislist = [2,4,3,5,1,10]
# output = 0
max_value = thislist[0]
for i in thislist:
    if max_value < i:
        max_value = i
        
print(max_value)

10


### Python program to find largest number in a list

In [25]:
thislist = [2,4,3,5,11,10]
min_value = thislist[0]
for i in thislist:
    if min_value>i:
        min_value = i
  
print(min_value)

2


### Reversing a List in Python

In [33]:
thislist = [10, 11, 12, 14, 13, 15]
# output = [15,13,14,12,11,10]
#new_list = thislist[::-1]
thislist.reverse()
print(thislist)

[15, 13, 14, 12, 11, 10]


### Python program to print even length words in a string

In [41]:
inpstr = "This is a python language"
words = inpstr.split()
for word in words:
    if len(word)%2==1:
        print(word)

a


### Program to print the strings which contains all vowels

In [47]:
inpstr = "ABeeIghiObhkUul"
inpstr = inpstr.lower()
print(inpstr)
vowels = ['a','e','i','o','u']
count = set()

for ch in inpstr:
    if ch in vowels:
        count.add(ch)

if len(count)==5:
    print("accepted")
else:
    print("not accepted")

abeeighiobhkuul
accepted


### Python program to add two Matrices

In [50]:
X = [[1,2,3],
    [4 ,5,6],
    [7 ,8,9]]

Y = [[9,8,7],
    [6,5,4],
    [3,2,1]]

result = [[0,0,0],
        [0,0,0],
        [0,0,0]]

for i in range(len(X)):
    for j in range(len(Y)):
        result[i][j] = X[i][j] + Y[i][j]
    
print(result)

[[10, 10, 10], [10, 10, 10], [10, 10, 10]]


In [56]:
X = [[1,2,3],
    [4 ,5,6],
    [7 ,8,9]]
  
Y = [[9,8,7],
    [6,5,4],
    [3,2,1]]
result = []
for t in zip(X, Y):
    temp = []
    for x in zip(*t):
        temp.append(sum(x))
    result.append(temp)
print(result)

[[10, 10, 10], [10, 10, 10], [10, 10, 10]]


### Create a Numpy array filled with all zeros

In [62]:
import numpy as np 
zero_array = np.zeros([3,3], int)
print(zero_array)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


### Find the most frequent value in a NumPy array

In [70]:
x = np.array([1,2,3,4,5,1,2,1,1,1])
# output = 1

count = np.bincount(x)
print(count)
# max_value = count[0]
# result = 0
# for ind, i in enumerate(count):
#     if max_value<i:
#         max_value = i
#         result = ind
# print(result)
print(count.argmax())
print(np.bincount(x).argmax())

[0 5 2 1 1 1]
1
1


In [72]:
gfg = np.matrix('[1, 2, 3; 4, 5, 6; 7, 8, 9]')
print(gfg.max())

9


In [78]:
X = np.array([[1,2,3],[4 ,5,6],[7 ,8,9]])

max_value = 0

for i in np.nditer(X):
    if max_value<i:
        max_value = i
print(max_value)

9


In [ ]:
X = np.array([[1,2,3],[4 ,5,6],[7 ,8,9]])
# ouput = 45

### Replace NumPy array elements that doesn’t satisfy the given condition

In [84]:
arr = np.array([5,3,4,7,8])
# ouput = [0,3,4,0,0]
arr[(arr%2==1)&(arr>5)] = -1
print(arr)

[ 5  3  4 -1  8]
