# Numpy

In [ ]:
! pip install numpy

In [2]:
import numpy as np

In [3]:
arr = np.array((1, 2, 3, 4, 5))
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [5]:
# 0 d array
arr = np.array(42)
print(arr)

42


In [6]:
# 1 d array 
arr = np.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]


In [7]:
# 2 d array

arr = np.array([[1, 2, 3], [4, 5, 6], [7,8,9]])
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [7]:
# 3 d array
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [9]:
# check the dimensions

a = np.array([1, 2, 3, 4, 5])
b = np.array([[1, 2, 3], [4, 5, 6], [7,8,9]])
c = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
if a.ndim==1:    
    print("This is a 1 d array")
print(b.ndim)
print(c.ndim)

This is a 1 d array
2
3


In [12]:
arr = np.array([1, 2, 3, 4, 4])
print(arr[1])

2


In [13]:
arr = np.array([1, 2, 3, 4])
print(arr[2] + arr[3])

7


In [15]:
1,2,3,4,5
6,7,8,9,10
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print(arr)
print(arr[0,2])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
3


In [27]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(arr)
print(arr[0])

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
[[1 2 3]
 [4 5 6]]


In [19]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[:3])

[1 2 3]


In [20]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[:4])

[1 2 3 4]


In [23]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[-4:-2])

[4 5]


In [32]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
#print(arr[start:end:step])
print(arr[1:5:2])

[2 4]


In [37]:
arr = np.array([10, 20, 30, 40, 50, 60, 70])
print(arr[0:4:3])

[10 40]


In [38]:
arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
print(arr)
print(x)

[1 2 3 4 5]
[1 2 3 4 5]


In [39]:
1 2 3 4
5 6 7 8
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(arr.shape)

(2, 4)


In [39]:
arr = np.array([1, 2, 3, 4], ndmin=5)
print(arr)
print('Shape of array :', arr.shape)

[[[[[1 2 3 4]]]]]
Shape of array : (1, 1, 1, 1, 4)


In [42]:
# Convert 1d array to 2d array
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr.reshape(4,3)
print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [15]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr.reshape(2, 3, 2)
print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [43]:
# flatenning arrays 
arr = np.array([[1, 2, 3], [4, 5, 6]])
newarr = arr.reshape(-1)
print(newarr)

[1 2 3 4 5 6]


In [44]:

arr = np.array([[1, 2, 3], [4, 5, 6]])
for x in arr:
    print(x,"\n")

[1 2 3] 

[4 5 6] 



In [45]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
for x in arr:
    for y in x:
        print(y)

1
2
3
4
5
6


In [46]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
for x in np.nditer(arr):
    print(x)

1
2
3
4
5
6


In [49]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for x in np.nditer(arr[:, ::2]):
  print(x)

1
3
5
7


In [47]:
arr = np.array([1, 2, 3])
for idx, x in np.ndenumerate(arr):
  print(idx[0], x)

0 1
1 2
2 3


In [55]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for idx, x in np.ndenumerate(arr):
    print(idx, x)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8


In [48]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.concatenate((arr1, arr2))
print(arr)

[1 2 3 4 5 6]


In [90]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
arr = np.concatenate((arr1, arr2),axis=1)
print(arr)

[[1 2 5 6]
 [3 4 7 8]]


In [56]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.stack((arr1, arr2), axis=1)

print(arr)

[[1 4]
 [2 5]
 [3 6]]


In [63]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.vstack((arr1, arr2))
print(arr)

[[1 2 3]
 [4 5 6]]


In [64]:
arr = np.array([1, 2, 3, 4, 5, 6])
newarr = np.array_split(arr, 3)
print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [65]:
arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 4)

print(newarr)

[array([1, 2]), array([3, 4]), array([5]), array([6])]


In [66]:
arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 3)

print(newarr[0])
print(newarr[1])
print(newarr[2])

[1 2]
[3 4]
[5 6]


In [67]:
arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])

newarr = np.array_split(arr, 3)

print(newarr)

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]


In [68]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.array_split(arr, 3, axis=1)

print(newarr)

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


In [66]:
arr = np.array([1, 2, 3, 4, 5, 4, 4])
x = np.where(arr%2==0)
print(x)

(array([1, 3, 5, 6]),)


In [85]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
x = np.where(arr%2==0)
print(x)

(array([6]),)


In [74]:
arr = np.array([3, 2, 0, 1])
new_arr = np.sort(arr)
print(new_arr)

[0 1 2 3]


In [76]:
arr = np.array([[3, 2, 4], [5, 0, 1]])
print(np.sort(arr))

[[2 3 4]
 [0 1 5]]


# Filter 

In [77]:
arr = np.array([41, 42, 43, 44])

x = [True, False, True, False]

newarr = arr[x]

print(newarr)

[41 43]


In [88]:
arr = np.array([41, 42, 43, 44])

newarr = arr[(arr%2==1) & (arr>41)]

print(newarr)

[43]


# Universal Functions 

In [91]:
arr1 = np.array([10, 11, 12, 13, 14, 15])
arr2 = np.array([20, 21, 22, 23, 24, 25])
newarr = np.add(arr1, arr2)
print(newarr)

[30 32 34 36 38 40]


In [95]:
arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([20, 21, 22, 23, 24, 25])
newarr = np.subtract(arr2, arr1)
print(newarr)

[ 10   1  -8 -17 -26 -35]


In [2]:
arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([20, 21, 22, 23, 24, 25])
newarr = np.multiply(arr1, arr2)
print(newarr)

[ 200  420  660  920 1200 1500]


In [4]:
arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([3, 5, 10, 8, 2, 33])
newarr = np.divide(arr1, arr2)
print(newarr)

[ 3.33333333  4.          3.          5.         25.          1.81818182]


In [93]:
arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([2, 2, 2, 2, 2, 2])
newarr = np.power(arr1, arr2)
print(newarr)

[ 100  400  900 1600 2500 3600]


In [94]:
arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([3, 7, 9, 8, 2, 33])
newarr = np.mod(arr1, arr2)
print(newarr)

[ 1  6  3  0  0 27]


In [7]:
arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([3, 7, 9, 8, 2, 33])
newarr = np.divmod(arr1, arr2)
print(newarr)

(array([ 3,  2,  3,  5, 25,  1]), array([ 1,  6,  3,  0,  0, 27]))


In [96]:
arr = np.trunc([50.50, 45.555, 37.56])
print(arr)

[50. 45. 37.]


In [97]:
arr = np.around(3.1666, 3)
print(arr)

3.167


In [12]:
arr = np.floor([3.1666, 3.6667])
print(arr)

[3. 3.]


In [13]:
arr = np.ceil([3.1666, 3.6667])
print(arr)

[4. 4.]


In [98]:
arr = np.arange(1, 15)
print(arr)
print(np.log(arr))

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[0.         0.69314718 1.09861229 1.38629436 1.60943791 1.79175947
 1.94591015 2.07944154 2.19722458 2.30258509 2.39789527 2.48490665
 2.56494936 2.63905733]


In [103]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([1, 4, 3])
newarr = np.sum([arr1,arr2])
print(newarr)

14


In [102]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([1, 4, 3])

newarr = np.sum([arr1, arr2], axis=1)

print(newarr)

[6 8]


In [25]:
arr = np.array([1, 2, 3, 4])
x = np.prod(arr)
print(x)

24


In [27]:
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([5, 6, 7, 8])
newarr = np.prod([arr1, arr2], axis=1)
print(newarr)

[ 5 12 21 32]


In [28]:
arr = np.array([10, 15, 25, 5])
newarr = np.diff(arr)
print(newarr)

[  5  10 -20]


In [31]:
arr = np.array([10, 15, 25, 5])
newarr = np.diff(arr, n=3)
print(newarr)

# [5,10,-20]
# [5, -30]
# [-35]

[  5  10 -20]


In [106]:
#LCM
num1 = 5
num2 = 6
x = np.lcm(num1, num2)
print(x)

# 1, 2, 3, 4, 5, 6, 7,8,9,10,11,12 

30


In [107]:
arr = np.array([3, 6, 9, 18])
x = np.lcm.reduce(arr)
print(x)

18


In [38]:
# 24 = 2*2*2*3
# 36 = 2*2*3*3
num1 = 24
num2 = 36
x = np.gcd(num1, num2)
print(x)

12


In [108]:
arr = np.array([20, 8, 32, 36, 16])
x = np.gcd.reduce(arr)
print(x)

4


In [109]:
arr = np.array([1, 1, 1, 2, 3, 4, 5, 5, 6, 7])
x = np.unique(arr)
print(x)

[1 2 3 4 5 6 7]


In [110]:
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([3, 4, 5, 6])
newarr = np.union1d(arr1, arr2)
print(newarr)

[1 2 3 4 5 6]


In [111]:
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([3, 4, 5, 6])
newarr = np.intersect1d(arr1, arr2, assume_unique=True)
print(newarr)

[3 4]


In [112]:
set1 = np.array([1, 2, 3, 4])
set2 = np.array([3, 4, 5, 6])
newarr = np.setdiff1d(set1, set2, assume_unique=True)
print(newarr)

[1 2]


In [113]:
set1 = np.array([1, 2, 3, 4])
set2 = np.array([3, 4, 5, 6])
newarr = np.setxor1d(set1, set2, assume_unique=True)
print(newarr)

[1 2 5 6]


In [48]:
arr = np.array([-1, -2, 1, 2, 3, -4])
newarr = np.absolute(arr)
print(newarr)

[1 2 1 2 3 4]


In [117]:
from math import log
import numpy as np

nplog = np.frompyfunc(log, 2, 1)

print(nplog(100, 2.73))

4.585445391918477


In [119]:
import numpy as np
arr = np.arange(1, 11)
print(arr)
x = np.lcm.reduce(arr)
print(x)

[ 1  2  3  4  5  6  7  8  9 10]
2520
